version: '3.3'

services:
  app:
    container_name: app
    image: itayg98/zoo-app:2.0
    build: 
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
        - "3000:80"
        - "3001:433"
    networks:
      - db-bridge
  db:
    container_name: db
    environment:
       ACCEPT_EULA : Y
       MSSQL_SA_PASSWORD : 1234ABCD@
    image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
    restart: always
    ports:
      - "1433:1433"
    networks:
      - db-bridge
networks:
    db-bridge: {}
